// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTqRU6gbBxRpeRHSpDqR_AxNlWZn9uyE',
    appId: '1:1143977671:web:2f09a03d9897385f6b70e2',
    messagingSenderId: '1143977671',
    projectId: 'flutter-4b772',
    authDomain: 'flutter-4b772.firebaseapp.com',
    storageBucket: 'flutter-4b772.firebasestorage.app',
    measurementId: 'G-66V9BYPQES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDX5aNW6ayirPUD8I3JrSTiIsH9rxWv4',
    appId: '1:1143977671:android:38f585bde12389066b70e2',
    messagingSenderId: '1143977671',
    projectId: 'flutter-4b772',
    storageBucket: 'flutter-4b772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLPxW7qlsyf9bd0_hDcA8VOXUjyy4aT4',
    appId: '1:1143977671:ios:70ea0b4b57af05386b70e2',
    messagingSenderId: '1143977671',
    projectId: 'flutter-4b772',
    storageBucket: 'flutter-4b772.firebasestorage.app',
    iosBundleId: 'com.example.myApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLPxW7qlsyf9bd0_hDcA8VOXUjyy4aT4',
    appId: '1:1143977671:ios:70ea0b4b57af05386b70e2',
    messagingSenderId: '1143977671',
    projectId: 'flutter-4b772',
    storageBucket: 'flutter-4b772.firebasestorage.app',
    iosBundleId: 'com.example.myApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTqRU6gbBxRpeRHSpDqR_AxNlWZn9uyE',
    appId: '1:1143977671:web:2999f3e7021b47956b70e2',
    messagingSenderId: '1143977671',
    projectId: 'flutter-4b772',
    authDomain: 'flutter-4b772.firebaseapp.com',
    storageBucket: 'flutter-4b772.firebasestorage.app',
    measurementId: 'G-SKFDY0WW99',
  );
}
